apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-app-ingress
  namespace: bu-a-workloads
  annotations:
    kubernetes.io/ingress.class: haproxy
spec:
  rules:
  - host: sample-app-bu-a-pr.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sample-app
            port:
              number: 80
